steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/digital-is-ops-sandbox-01/flask-wxcc-api', '.']

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/digital-is-ops-sandbox-01/flask-wxcc-api']

  # Step 3: Deploy the image to Google Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'flask-wxcc-api',
           '--image', 'gcr.io/digital-is-ops-sandbox-01/flask-wxcc-api',
           '--platform', 'managed',
           '--region', 'us-central1',  # Set your preferred region
           '--allow-unauthenticated']

images:
  - 'gcr.io/digital-is-ops-sandbox-01/flask-wxcc-api'